### ISSUE TITLE
How to fix the time?

### ISSUE THREAD

**Issue by 24Harren** [chocolatkey/FoOlSlide2#10]
Hi, how can I fix the time of publication?
Looks like this "-0001.11.30 "

Thx in advance.

**Comment by chocolatkey** [comment]
Please read what I said in the releases section and the readme: **Current stable version: 2.4.0 (_unstable_). Use releases tab to download if you want stability**. Use 2.3.3

**Comment by 24Harren** [comment]
Sorry, and thx ;D
