### ISSUE TITLE
Incomplete Install

### ISSUE THREAD

**Issue by perrinaz** [chocolatkey/FoOlSlide2#17]
Ok, I would have asked in a more discussion oriented forum but I could not find one.

Problem: Installing does not complete with no obvious error messages.  Discovered that fs_users fails to create and the installation stops there.  When I look deeper, it does not like the format of the datetime and timestamp default value formats (datetime has to be 1000-..., timestamp has to start with 1970-...).  Everytime I get a little further, I seem to get tripped up with default values.  I know other people are using this so I am thinking there is an error in my copy because I cannot imagine that anyone else has this problem without it getting back to the development staff.  The furthest I got by making changes to the code to add default values is an install that looks like it finished correctly and will display the reader screen (with no chapters) but the admin screen still has errors.  I cannot get to the admin page so I cannot provide a system information dump.  

OS: Ubuntu 16.04
PHP: v7.0.22
MySQL: 5.7.19
Foolslide Tags tried both 2.4.0 and master

**Comment by chocolatkey** [comment]
Sorry, FoOlslide2 is never going to work properly with PHP 7. I tried but it's core is just too old, that's why I'm completely rewriting it as FoOlSlideX

**Comment by perrinaz** [comment]
I've actually gotten it to work -- so far.  At least, for what limited purposes I want.  Created date isn't set right and you *have* to have a volume number but those are livable for now :)
