### ISSUE TITLE
Can't add Chapters, Series and Teams

### ISSUE THREAD

**Issue by Shirobaka** [chocolatkey/FoOlSlide2#19]
Hi,
since a few days i have following error when i try to add a new Chapter to a manga.
![chrome_2017-09-11_16-46-12](https://user-images.githubusercontent.com/8634317/30280815-0d196132-9711-11e7-9924-ff96f8f1c69f.png)

A smilliar error even shown when i try to add teams or new series.
A few days ago it works all fine, i haven't changed anything so i can't explain how it can't work anymore.

**Comment by chocolatkey** [comment]
Please include foolslide and php version

**Comment by Shirobaka** [comment]
@chocolatkey 

```
Server Information
------------------------------
Web Server Software = Apache
PHP Version = 5.6.31-4+0~20170804100521.6+jessie~1.gbpea630b

Software Information
------------------------------
FoOlSlide Version = 2.3.3
Environment = Production

PHP Configuration
------------------------------
php.ini Location = /etc/php/5.6/fpm/php.ini
Safe Mode = Off
Allow URL fopen = On
Max Execution Time = 180
File Uploads = Enabled
Max POST Size = 512M
Max Upload Size = 128M
Max File Uploads = 64

Extensions
------------------------------
cURL = Installed
GD2 = Installed

Report Generated: Tue, 12 Sep 17 16:12:42 +0200
```

**Comment by chocolatkey** [comment]
Do you know how to use phpmyadmin / do you have it installed?

**Comment by chocolatkey** [comment]
https://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values I think it's this "STRICT_TRANS_TABLES" mode. Use Phpmyadmin or edit the configuration directly

**Comment by Shirobaka** [comment]
Works fine now, thank you.
