### ISSUE TITLE
Upgrading from administration

### ISSUE THREAD

**Issue by Ripper346** [chocolatkey/FoOlSlide2#2]
Hi, I have two readers in different servers and I get the message: "GitHub could not be contacted: impossible to check for new versions.". The version installed is the last commit on 26th march.
Screenshot: http://prntscr.com/aoirhk
Can you fix it?

**Comment by chocolatkey** [comment]
I am working on the upgrade functionality and will get it working as fast as possible. I'll probably release it as 2.3. Thanks for your feedback

**Comment by Ripper346** [comment]
Thank you!

**Comment by chocolatkey** [comment]
Sorry for taking so long. 2.3 is done
