### ISSUE TITLE
Severity: Warning

### ISSUE THREAD

**Issue by ma57al91fr87** [chocolatkey/FoOlSlide2#3]
ERROR - 2016-08-02 14:09:13 --> Severity: Warning  --> Creating default object from empty value /home/bshhssd/public_html/application/models/team.php 74

**Comment by chocolatkey** [comment]
Could you post your server info please? Also does this prevent you from logging in, does it mess up he entire site? Are you able to install? What exactly happened

**Comment by ma57al91fr87** [comment]
Server Information
------------------------------
Web Server Software = Apache
PHP Version = 5.5.38

Software Information
------------------------------
FoOlSlide Version = 2.2.2
Environment = Production

PHP Configuration
------------------------------
php.ini Location = /opt/alt/php55/etc/php.ini
Safe Mode = Off
Allow URL fopen = On
Max Execution Time = 300
File Uploads = Enabled
Max POST Size = 64M
Max Upload Size = 64M
Max File Uploads = 20

Extensions
------------------------------
cURL = Installed
GD2 = Installed

I've upgraded from v 0.8.19 to 2.2.2
Now when i try do add a new series nothing happens(as if i refresh the page ) and i see that error on the log file

**Comment by chocolatkey** [comment]
That's strange. I don't get that error when I do a fresh install. Did you install using the previous database? And what teams are present on the team page:
![image](https://cloud.githubusercontent.com/assets/13407784/17342279/cdc5522c-58f8-11e6-938b-b8ea017f8555.png)

**Comment by ma57al91fr87** [comment]
i know it's very strange because i also  try to replicate this problem with a fresh install but i don't get that error...
Anyway i use a previous database.

On the team page there are these two teams
![schermata del 2016-08-02 21-43-31](https://cloud.githubusercontent.com/assets/20794341/17342723/c2db2560-58fa-11e6-832e-f33a57d47734.png)

**Comment by chocolatkey** [comment]
Could you give me an SQL dump of your database (of course you can remove the user accounts)? Then I can duplicate your setup and see how to fix it.

**Comment by ma57al91fr87** [comment]
Of course man!

[db.sql.zip](https://github.com/chocolatkey/FoOlSlide2/files/398900/db.sql.zip)

I know its a little "messy" (full of comics from 2012) but only yesterday i replaced  the ex-admin...

**Comment by chocolatkey** [comment]
![image](https://cloud.githubusercontent.com/assets/13407784/17364175/0427fc58-597f-11e6-80db-a027a827ca27.png)
I duplicated your foolslide with that database (just my user and profile) and I didn't have a problem creatinga new series. I am running a different PHP version though. Would you mind upgrading to version 2.3.1 (**and change your theme folder and reader_config.php of theme so it doesn't get overwritten by updates and you might want to add the new changes I made to style.css and reader.php with the search button**) so that I can be 100% sure it's not the fault of the version you are working on (and so I can just update it if we fix this and you can automatically update foolslide now)

**Comment by ma57al91fr87** [comment]
all right, I'll let you know after i finish to upgrading

**Comment by ma57al91fr87** [comment]
i upgraded all the file but now i can't logging...
The loggin page(and all the admin page) load forever

**Comment by chocolatkey** [comment]
How did you upgrade?

**Comment by chocolatkey** [comment]
Just delete all files except the content folder and config.php and then overwrite from the new zip

**Comment by ma57al91fr87** [comment]
like before
-I delete from ftp all files except the content folder and config.php
-I upload all the new files (extracted from FoOlSlide2-2.3.1.zip)
I can't logging...

**Comment by chocolatkey** [comment]
Ohhhh I know what the problem is sorry

**Comment by chocolatkey** [comment]
It's because your SSL config is messed up (see https://github.com/chocolatkey/FoOlSlide2/commit/1021c426caf4d20d2658821dd165070e19660873) You can manually undo those changes

**Comment by chocolatkey** [comment]
Actually wait a minute I'll deploy a new version

**Comment by chocolatkey** [comment]
Ok use 2.3.2 and in /application/config/constants.php set FORCE_SSL to false

**Comment by ma57al91fr87** [comment]
ehm in  in /application/config/constants.php  there isn't  FORCE_SSL ^^"

**Comment by chocolatkey** [comment]
Sorry I didn't press the sync button on my github client on my PC. Please download 2.3.2 again, it should be there

**Comment by ma57al91fr87** [comment]
I still can't add new comics

Also on log

ERROR - 2016-08-03 15:29:30 --> Severity: Notice  --> Undefined index: HTTPS /home/bgpzslsl/public_html/application/views/admin/default.php 2

**Comment by chocolatkey** [comment]
Yeah...ok next thing: in index.php change this: define('ENVIRONMENT', 'production'); to this define('ENVIRONMENT', 'development'); And tell me which errors you get on the page when you try to add a new series

**Comment by ma57al91fr87** [comment]
Nothing....sometimes i'm redirect to index.php sometimes the page simply refresh

By the way in all the admin page i've this
```
A PHP Error was encountered

Severity: Notice

Message: Undefined index: HTTPS

Filename: admin/default.php

Line Number: 2
```

**Comment by chocolatkey** [comment]
And you check permissions right?

**Comment by ma57al91fr87** [comment]
I think that the permissions are right

**Comment by chocolatkey** [comment]
100% sure? Because that's the last thing I can guess is wrong without physical access

**Comment by ma57al91fr87** [comment]
i check the chmod and they are
0755 for folders
0644 for files

**Comment by chocolatkey** [comment]
Please make it 0777 for folders and 0777 for files except config.php (0644)

**Comment by ma57al91fr87** [comment]
same as before

**Comment by chocolatkey** [comment]
To continue I would need direct access, because otherwise I have no idea.

**Comment by ma57al91fr87** [comment]
In the end i'v reinstallled fooslide and now everything seems OK... seriously don't know what happend.
Anyway thank's for your support and for your hard work with this project!

**Comment by chocolatkey** [comment]
You're welcome. One day someone will uncover this bug....

**Comment by ma57al91fr87** [comment]
i've a question for you...What is the best php version to use with foolslide?

**Comment by chocolatkey** [comment]
The latest PHP 5.6.xx
