### ISSUE TITLE
Upgrading from Original Foolslide

### ISSUE THREAD

**Issue by Mistblown** [chocolatkey/FoOlSlide2#4]
I have what I _think_ is kind of a weird issue. Not sure though.
I'm trying to upgrade to this from the original Foolslide (while a full wipe is recommended, it is possible, yes?). I followed the directions here for a manual upgrade: http://foolcode.github.io/FoOlSlide/

Now, this results in a working front end, but if I try to go to the admin panel, it automatically switches the domain from http to https and refuses to connect. I have no issue browsing the public part of the site, it's just the admin panel and profile stuff. Any ideas?

**Comment by chocolatkey** [comment]
Yeah that's because I modified it so it forces https in the admin backend because http is insecure. If your host does not support https for whatever reason, you can allow http in the backend by editing the value for FORCE_SSL to false in /application/config/constants.php
