### ISSUE TITLE
A database error ocurred

### ISSUE THREAD

**Issue by 24Harren** [chocolatkey/FoOlSlide2#6]
"Unable to connect to your databse server using the provide setting. 
Filename: Core/loader.php
Line number: 268"

Hi bro, thank you for the version, but I got this error after try to upload the first chap.
I can't enter to foolslide. 

Edit: The issue is fixed, so don't worry, don't know what happened.
 I've installed Disqus and the comment box appears on every page, and I just want to appear in the pages of the chapters. Any solution?

Thanks in advance.

**Comment by 24Harren** [comment]
Me again, the issue is fixed, so don't worry, don't know what happened.

Another question, actually disquss is supported?

**Comment by chocolatkey** [comment]
I'll be releasing a new version where you can change disqus settings from the admin panel as soon as I have time

**Comment by 24Harren** [comment]
Thank you :D
